services:
  idkibackend:
    image: indoaoe-img
    container_name: indoaoe-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - indoaoe_vendor:/var/www/vendor
    ports:
      - "8000:8000"
    # working_dir: /var/www
    networks:
      - nginx
      - postgres

volumes:
  indoaoe_vendor:
    name: indoaoe_vendor

networks:
  postgres:
    external: true
  nginx:
    external: true
